# This workflow will do a clean install of node dependencies,
# build the source code and run tests

name: CD

on:
  push:
    branches: [main]

jobs:
  website:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # minimum version supported by our dependencies (Jest)
          node-version: 14.17

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - run: cd website && yarn install
      - run: cd website && yarn compile
      - run: cd website && yarn test
      - run: cd website && yarn deploy
