# This workflow will do a clean install of node dependencies,
# build the source code and run tests

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "**"

jobs:
  website:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          # minimum version supported by our dependencies (Jest)
          node-version: 14.15

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - run: cd website && yarn install
      - run: cd website && yarn compile
      - run: cd website && yarn build
      - run: cd website && yarn test
